apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    url: database:5432
    database: postgres
    user: postgres
    secureJsonData:
      password: 'postgres'
    jsonData:
      sslmode: 'disable'
      maxOpenConns: 0
      maxIdleConns: 2
      connMaxLifetime: 14400
      postgresVersion: 14
      timescaledb: false
