# Generated by Django 3.1.7 on 2022-04-29 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0003_logger_function_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='logger',
            name='user_uuid',
            field=models.UUIDField(null=True),
        ),
    ]
