# Generated by Django 3.1.7 on 2022-05-04 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0005_auto_20220429_1309'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logger',
            old_name='user_uuid',
            new_name='user_pk',
        ),
    ]
