# Generated by Django 3.1.7 on 2022-04-27 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Logger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gql_query_name', models.CharField(blank=True, max_length=100, null=True)),
                ('sql_query_count', models.IntegerField(null=True)),
                ('sql_query_time', models.IntegerField(null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
