# Generated by Django 3.1.7 on 2022-04-27 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logger',
            name='sql_query_time',
            field=models.FloatField(null=True),
        ),
    ]
