# Generated by Django 3.1.7 on 2022-04-29 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0002_auto_20220427_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='logger',
            name='function_time',
            field=models.FloatField(null=True),
        ),
    ]
