# Generated by Django 3.1.7 on 2022-05-04 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0007_logger_user_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='logger',
            name='remote_addr',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
